/**
 * NewStudentWindow Class
 * A Window which acts as the front-end for the user to the Controller object
 * Project 2: SIMS GUI Project
 * @author Daniel Dymond (Group 1 - ID# 17977610) 2020
 */
package Views;

import java.awt.event.ActionListener;


public class NewStudentWindow extends javax.swing.JInternalFrame
{
    ActionListener actionListener;

    /**
     * Creates new StudentDetailsWindow
     * @param actionListener ActionListener from the Controller
     */
    public NewStudentWindow(ActionListener actionListener) {
        this.actionListener = actionListener;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        tipText = new javax.swing.JLabel();
        enrollStudentButton = new javax.swing.JButton();
        enrollStudentButton.addActionListener(actionListener);
        cancelButton = new javax.swing.JButton();
        cancelButton.addActionListener(actionListener);
        studentDetailsPanel = new Views.StudentDetailPanel();

        setClosable(true);
        setIconifiable(true);
        setTitle("New Student");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/img/user-add-32px.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/img/user-add-32px.png"))); // NOI18N
        jLabel5.setText("Create New Student");

        tipText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/img/bulb-16px.png"))); // NOI18N
        tipText.setText("Please fill all the fields to create the new Student object.");

        enrollStudentButton.setText("Enroll Student");

        cancelButton.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tipText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enrollStudentButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studentDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipText)
                    .addComponent(enrollStudentButton)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton cancelButton;
    public javax.swing.JButton enrollStudentButton;
    private javax.swing.JLabel jLabel5;
    public Views.StudentDetailPanel studentDetailsPanel;
    private javax.swing.JLabel tipText;
    // End of variables declaration//GEN-END:variables

    
}
