/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import java.awt.event.ActionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danie
 */
public class SearchStudentWindow extends javax.swing.JInternalFrame {
    
    ActionListener actionListener;
    DefaultTableModel tableModel;
    
    /**
     * Creates new form SearchStudentWindow
     */
    public SearchStudentWindow(ActionListener actionListener, DefaultTableModel tableModel) {
        this.actionListener = actionListener;
        this.tableModel = tableModel;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchRadioGroup = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        heroLabel = new javax.swing.JLabel();
        searchByIDRadio = new javax.swing.JRadioButton();
        searchByNameRadio = new javax.swing.JRadioButton();
        studentIDField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        searchByIDButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        searchByNameButton = new javax.swing.JButton();
        searchByNameButton.addActionListener(actionListener);
        selectStudentButton = new javax.swing.JButton();
        searchByNameButton.addActionListener(actionListener);
        jScrollPane3 = new javax.swing.JScrollPane();
        studentSearchResultsTable = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Search Student");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/img/user-32px.png"))); // NOI18N

        heroLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        heroLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/img/user-32px.png"))); // NOI18N
        heroLabel.setText("Search Student");

        searchRadioGroup.add(searchByIDRadio);
        searchByIDRadio.setSelected(true);
        searchByIDRadio.setText("Search by Student ID");
        searchByIDRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByIDRadioActionPerformed(evt);
            }
        });

        searchRadioGroup.add(searchByNameRadio);
        searchByNameRadio.setText("Search by Student Name");
        searchByNameRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByNameRadioActionPerformed(evt);
            }
        });

        studentIDField.setToolTipText("");

        jLabel1.setText("Student ID:");

        jLabel2.setText("First Name:");

        firstNameField.setToolTipText("");
        firstNameField.setEnabled(false);

        jLabel3.setText("Last Name:");

        lastNameField.setToolTipText("");
        lastNameField.setEnabled(false);

        searchByIDButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/img/find-16px.png"))); // NOI18N
        searchByIDButton.setToolTipText("Search for Student by Student ID");
        searchByIDButton.addActionListener(actionListener);

        searchByNameButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/img/find-16px.png"))); // NOI18N
        searchByNameButton.setToolTipText("Search for a Student by First and Last Name");
        searchByNameButton.setEnabled(false);

        selectStudentButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/img/right-green-arrow-16px.png"))); // NOI18N
        selectStudentButton.setToolTipText("Search for a Student by First and Last Name");
        selectStudentButton.setEnabled(false);

        studentSearchResultsTable.setAutoCreateRowSorter(true);
        studentSearchResultsTable.setModel(tableModel);
        studentSearchResultsTable.setCellSelectionEnabled(true);
        jScrollPane3.setViewportView(studentSearchResultsTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(searchByNameButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectStudentButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(heroLabel)
                            .addComponent(searchByIDRadio)
                            .addComponent(searchByNameRadio))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(studentIDField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchByIDButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lastNameField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(firstNameField)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(heroLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchByIDRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studentIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(16, 16, 16)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchByNameRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(searchByIDButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchByNameButton)
                    .addComponent(selectStudentButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchByIDRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByIDRadioActionPerformed
        if (searchByIDRadio.isSelected())
        {
            studentIDField.setEnabled(true);
            searchByIDButton.setEnabled(true);
            firstNameField.setEnabled(false);
            lastNameField.setEnabled(false);
            searchByNameButton.setEnabled(false);
            selectStudentButton.setEnabled(false);
            studentSearchResultsTable.setEnabled(true);
        }   
    }//GEN-LAST:event_searchByIDRadioActionPerformed

    private void searchByNameRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByNameRadioActionPerformed
        if (searchByNameRadio.isSelected())
        {
            studentIDField.setEnabled(false);
            searchByIDButton.setEnabled(false);
            firstNameField.setEnabled(true);
            lastNameField.setEnabled(true);
            searchByNameButton.setEnabled(true);
            selectStudentButton.setEnabled(true);
            studentSearchResultsTable.setEnabled(false);
        }   
    }//GEN-LAST:event_searchByNameRadioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField firstNameField;
    private javax.swing.JLabel heroLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JTextField lastNameField;
    public javax.swing.JButton searchByIDButton;
    private javax.swing.JRadioButton searchByIDRadio;
    public javax.swing.JButton searchByNameButton;
    private javax.swing.JRadioButton searchByNameRadio;
    private javax.swing.ButtonGroup searchRadioGroup;
    public javax.swing.JButton selectStudentButton;
    public javax.swing.JTextField studentIDField;
    public javax.swing.JTable studentSearchResultsTable;
    // End of variables declaration//GEN-END:variables
}
