/**
 * SessionWindow Class
 * A View which shows and hosts other windows.
 * Project 2: SIMS GUI Project
 * @author Daniel Dymond (Group 1 - ID# 17977610) 2020
 */
package Views;

import java.awt.event.ActionListener;

public class SessionWindow extends javax.swing.JFrame 
{
    ActionListener actionListener;

    /**
     * Creates new form SessionWindow
     * @param actionListener ActionListner Object from the Controller
     */
    public SessionWindow(ActionListener actionListener) {
        this.actionListener = actionListener;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        toolbar = new javax.swing.JToolBar();
        searchStudentButton = new javax.swing.JButton();
        createStudentButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        aboutButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Information Management System");
        setExtendedState(6);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1101, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );

        toolbar.setFloatable(false);
        toolbar.setRollover(true);

        searchStudentButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/img/user-32px.png"))); // NOI18N
        searchStudentButton.setText("Search Student...");
        searchStudentButton.setToolTipText("Search for a Student by either their Student ID or via their name");
        searchStudentButton.setFocusable(false);
        searchStudentButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        searchStudentButton.addActionListener(actionListener);
        toolbar.add(searchStudentButton);

        createStudentButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/img/user-add-32px.png"))); // NOI18N
        createStudentButton.setText("Create Student...");
        createStudentButton.setToolTipText("Create a new Student to add to the Institution");
        createStudentButton.setFocusable(false);
        createStudentButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        createStudentButton.addActionListener(actionListener);
        toolbar.add(createStudentButton);
        toolbar.add(jSeparator1);

        aboutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/img/info-32px.png"))); // NOI18N
        aboutButton.setText("About");
        aboutButton.setToolTipText("View Information about the Application.");
        aboutButton.setFocusable(false);
        aboutButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        aboutButton.addActionListener(actionListener);
        toolbar.add(aboutButton);
        aboutButton.getAccessibleContext().setAccessibleDescription("See information about this application");

        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/img/lock-32px.png"))); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.setToolTipText("Logout and return to the Log In screen.");
        logoutButton.setFocusable(false);
        logoutButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        logoutButton.addActionListener(actionListener);
        toolbar.add(logoutButton);
        toolbar.add(filler1);
        toolbar.add(filler2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
            .addComponent(toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, 1101, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(desktop))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton aboutButton;
    public javax.swing.JButton createStudentButton;
    public javax.swing.JDesktopPane desktop;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JToolBar.Separator jSeparator1;
    public javax.swing.JButton logoutButton;
    public javax.swing.JButton searchStudentButton;
    private javax.swing.JToolBar toolbar;
    // End of variables declaration//GEN-END:variables
}
